[package]
name = "two_five_eight_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
solana-client = "1.7.11"
solana-sdk = "1.7.11"
solana-py = "0.5.1"